# Generated by Django 3.1 on 2020-08-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(default='settings.MEDIA_ROOT/images/image_3.jpg', help_text='Set feature image', upload_to='media/images/'),
        ),
    ]
